apiVersion: v1
kind: Secret
metadata:
  name: simple-gitops-argocd-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "git@github.com:Dandi-Pangestu/simple-gitops-argocd-private.git"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAxK7RpCxpIDNL1uxpXU6INRUzV6dxltnuyAlgqXZFo9wAAAJgqZsJgKmbC
    YAAAAAtzc2gtZWQyNTUxOQAAACAxK7RpCxpIDNL1uxpXU6INRUzV6dxltnuyAlgqXZFo9w
    AAAED+wANM4kAxqWyecMhGPWifjeemsp0gVTGgjxMWkvXcnTErtGkLGkgM0vW7GldTog1F
    TNXp3GW2e7ICWCpdkWj3AAAAEGFyZ29jZEBkYW5kaS5jb20BAgMEBQ==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"